### PR TITLE
6178: Change text area to char count area

### PR DESCRIPTION
**Pull request by kat1906**

### CODE REVIEW

**Comment by kat1906** [comment]
when I was putting it in it worked fine when I hadn't linked in the js script - the word count didn't work but it displays something similar to what we put about the maximum word count. When you link in the js script file it then does the word count. I think if you don't enter a maxLength then it defaults to that too so that should be what our text area fields look like until we go through the manifests and add maxLength fields to them.

**Comment by kat1906** [comment]
I thought about doing it separately but they are similar enough for it not to make sense

**Comment by alibombaye** [comment]
In that case that's fine then. I was just little bit cautious about the non-js version. But this is even better since the component itself will deal with js and non-js version.

**Comment by kat1906** [comment]
I was going to fully test it in MP and if it doesn't work then revert but I think it will be fine - govuk guys know what they are doing 😜

**Pull request merged**
